name: Deploy CI/CD

on:
  push:
    branches:
     - main
     - develop

jobs:
  Run-CI-CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn

      - name: Running Build
        run: yarn run build

      - name: Running Deploy
        run: yarn run deploy
